### PR TITLE
Update state.js

### PR DESCRIPTION
**Pull request by kfahn22**
Add RATIONS, LANDMARKS, and OUTCOMES

Just first pass.  Didn't get all the way through the game so don't have all the Landmarks.
The probability of the outcome will depend on location.  Will have to think about how to incorporate.
Outcomes probably also needs a variable(s)?  to indicate what it affects and by how much, i.e dysentery affects passengers health, theft reduces inventory, etc..

### CODE REVIEW

**Comment by shiffman** [comment]
I'm wondering if most of this should actually be in separate JSON files, it is less about the active "state" of the game and more the data driving the game to look up? What do you think?

**Comment by kfahn22** [comment]
I think that makes sense.  Would you want a separate file for each major data type?  I also just realized that the version you are playing handles buying supplies differently from the one I was playing (where you can buy at forts).  Your version appears to only offer the option of trading, but maybe I am missing something.  Will have to set up exchange rates.  Also realized that hunting is important (when you run out of food), but involves setting up a way to hunt.  How involved do you want this to get?

**Comment by kfahn22** [comment]
I think that makes sense.  Would you want a separate file for each major data type?  I also just realized that the version you are playing handles buying supplies differently from the one I was playing (where you can buy at forts).  Your version appears to only offer the option of trading, but maybe I am missing something.  Will have to set up exchange rates.  Also realized that hunting is important (when you run out of food), but involves setting up a way to hunt.  How involved do you want this to get?

**Comment by kfahn22** [comment]
Sorry--I wasn't clear on what you were asking.  You want all the data in json format in the data folder, correct?

**Pull request closed without merging**
