### PR TITLE
User Input

### PR DESCRIPTION
**Pull request by shiffman**
Working on #8 in this branch! @Rodak123 do you think you could add a the "█" to your font? You'll see that I had to revert to `VT323` in order to display a cursor. Of course I could also use an image or draw a p5 rectangle if that's preferable? 

image

### CODE REVIEW

**Comment by shiffman** [comment]
If we want to be faithful to the original cursor:

Screen Shot 2022-11-20 at 9 01 35 PM

**Comment by Rodak123** [comment]
I'll add the original cursor to the font. (Once I get home from school)
But the "█" cursor should be already there.

**Comment by Rodak123** [comment]
Turns out I added the wrong cursor character to the original font, this one: "∎"
Now fixed in #25

**Comment by shiffman** [comment]
There's a lot more to do here but since the basic functionality is working (with a test that alllows the player to advance to the next slide after entering "1") I am going to merge. I'll be pretty busy this week with the holiday here in the US so may not return to working on this until next week.

**Pull request merged**
