### PR TITLE
Working on the learn slides

### PR DESCRIPTION
**Pull request by shiffman**

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @Rodak123 I started working with the `Slide` and `SlideManager` class attempting to create the "learn about the trail" slides: 

Screen Shot 2022-11-22 at 2 11 21 PM  Screen Shot 2022-11-22 at 2 11 21 PM 

What is the best way to proceed? Should I make this slide a new `type` (`"info"`?)  and then the slide will render based on its type? (Since there is no list of choices.)

```json
   {
      "name": "learn1",
      "type": "info",
      "data": {
        "title": "The Oregon Trail",
        "prompt": "Press SPACE BAR to continue",
        "img": "img/title.png",
        "content": {
          "text": "Try taking a journey by covered wagon across 2000 miles of plains, rivers, and mountains. Try! On the plains, will you slosh your oxen through mud and water-filled ruts or will you plod through dust six inches deep?",
          "textIndent": 2,
          "font": {
            "name": "CodeGon Mono",
            "file": "fonts/codegon-mono.ttf",
            "size": 7
          }
        }
      }
    },
```

**Comment by Rodak123** [comment]
I was thinking about making new classes for `choice` slides and `info` slides and any other types.
Essentially not using the original `Slide` class.

**Comment by Rodak123** [comment]
> Hi @Rodak123 I started working with the `Slide` and `SlideManager` class attempting to create the "learn about the trail" slides:
> 
> Screen Shot 2022-11-22 at 2 11 21 PM Screen Shot 2022-11-22 at 2 11 21 PM
> 
> What is the best way to proceed? Should I make this slide a new `type` (`"info"`?) and then the slide will render based on its type? (Since there is no list of choices.)
> 
> ```json
>    {
>       "name": "learn1",
>       "type": "info",
>       "data": {
>         "title": "The Oregon Trail",
>         "prompt": "Press SPACE BAR to continue",
>         "img": "img/title.png",
>         "content": {
>           "text": "Try taking a journey by covered wagon across 2000 miles of plains, rivers, and mountains. Try! On the plains, will you slosh your oxen through mud and water-filled ruts or will you plod through dust six inches deep?",
>           "textIndent": 2,
>           "font": {
>             "name": "CodeGon Mono",
>             "file": "fonts/codegon-mono.ttf",
>             "size": 7
>           }
>         }
>       }
>     },
> ```

Yes, 
I would do it like that

**Comment by Rodak123** [comment]
Maybe more like this, but I'm not sure
```json
{
  "name": "learn1",
  "type": "info",
  "data": {
    "title": "The Oregon Trail",
    "prompt": "Press SPACE BAR to continue",
    "text": "Try taking a journey by covered wagon across 2000 miles of plains, rivers, and mountains. Try! On the plains, will you slosh your oxen through mud and water-filled ruts or will you plod through dust six inches deep?",
    "action": {
      "type": "changePage",
      "newPageName": "main_menu"
    },
    "img": "img/title.png",
    "content": {
      "textIndent": 2,
      "font": {
        "name": "CodeGon Mono",
        "file": "fonts/codegon-mono.ttf",
        "size": 7
      }
    }
  }
}
```
Also a text wrapping feature is needed or the text can be formatted into an array like such:
```json
"text": ["Try taking a journey by","covered wagon across 2000","miles of plains, rivers, and","mountains.  Try! On the","plains, will you slosh your","oxen through mud and","water-filled ruts or will you plod through dust six inches","deep?"]
```

**Comment by Rodak123** [comment]
@shiffman 
#34 I've added a slide type for the `choice` slides

The slide manager calls a `loadSlide` function witch chooses the correct slide type

If you already implemented types, than i can remove my solution.

**Comment by shiffman** [comment]
Also, for word wrapping the `text()` function in p5.js takes a width and height argument to fit within a box. That's likely better than manually breaking apart the text.

**Comment by shiffman** [comment]
@Rodak123 I think I merged everything from here together with your recent work. I'm going to merge this into main, feel free to check if I lost any changes you made by accident.

**Pull request merged**
