### PR TITLE
Text Wrap

### PR DESCRIPTION
**Pull request by shiffman**
Working on #39 in this branch.

### CODE REVIEW

**Comment by shiffman** [comment]
@Rodak123 I added text wrap though it's not really tested beyond the one page. I noticed a couple things with the font.

1. Missing "-" character for "water-filled"
2. The line-height is very compressed, is this a font setting or something to add in the code?

Screen Shot 2022-11-24 at 10 33 15 AM Screen Shot 2022-11-24 at 10 33 08 AM

**Comment by shiffman** [comment]
This is the non-mono font, the letter spacing is better but the SPACE character itself is off I believe?

Screen Shot 2022-11-24 at 10 37 30 AM

**Comment by Rodak123** [comment]
@shiffman I updated the font in #42

**Comment by shiffman** [comment]
There is a lot more to be done here but going to merge this as the foundation is there.

**Pull request merged**
